### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Zibri** [chrivers/samsung-firmware-magic#9]
file: Samsung_SSD_850_EVO_EMT02B6Q_Win.iso

```
$ python3 ~/samsung-magic.py <DSRD.enc >DSRD.xml
Traceback (most recent call last):
  File "/home/zibri/samsung-magic.py", line 51, in <module>
    aes = AES.new(key, AES.MODE_ECB)
  File "/home/zibri/.local/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/home/zibri/.local/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/home/zibri/.local/lib/python3.10/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

**Comment by yssreddy1961** [comment]
i think the  error  came because of  pycrypto python module.

pl uninstall pycrypto module  and install pycryptodome  module  by pip install pycryptodome
and  verify it solved or not
